######################################################################
//for  users
###
POST http://localhost:5000/api/v1/users/user HTTP/1.1
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "firstName": "Jane",
  "lastName" : "Doe",
  "username": "admin",
  "password": "password",
  "address" : "LA"

}

###
POST http://localhost:5000/api/v1/users/login HTTP/1.1
Content-Type: application/json

{
   "email": "john53@gmail.com",
  "password": "missionaccomplished@009"
}

###
PATCH http://localhost:5000/api/v1/users/62278133b1e61a49bc63edec/product/62277da1d2b3a856fca8ce03

###
DELETE http://localhost:5000/api/v1/users/622a245006cc0d3774d9adfa

###
GET http://localhost:5000/api/v1/users
Content-Type: application/json

###
GET http://localhost:5000/api/v1/users/622a233fe9557f16902cda96

###
PUT http://localhost:5000/api/v1/users/622a233fe9557f16902cda96
Content-Type: application/json

{
    "isBanned": false,
	"isAdmin": false
}

###



######################################################################
//for movies
###
POST http://localhost:5000/api/v1/movies/movie HTTP/1.1
Content-Type: application/json

{
	"id": 14,
	"title": "Black Panther",
	"year": "2018",
	"genres": ["Action", "Adventure", "Sci-Fi"],
	"director": "Ryan Coogler",
	"stars": {
		"rate": 7.3,
		"count": 714000
	},
	"description": "T'Challa, heir to the hidden but advanced kingdom of Wakanda, must step forward to lead his people into a new future and must confront a challenger from his country's past.",
	"image": "https://www.kino.dk/sites/default/files/movie-posters/adrift-plakat_5ae8676a3e7ae.jpg"
}

###
DELETE http://localhost:5000/api/v1/movies/6241f447ff8e7840642b0103

###
GET http://localhost:5000/api/v1/movies
#Access-Control-Allow-Origin: *

###
GET http://localhost:5000/api/v1/movies/62277ff5ec31a918dc93efb9

###
PUT http://localhost:5000/api/v1/movies/624314983500895860f7042b
Content-Type: application/json

{
	"funfacts": "The name of the fictional land Wakanda was given after the Wakamba aka Kamba tribe inhabiting Kenya.  The film was released in February, which is officially marked as Black History month across U.S. and Canada. "
 
}

